# Generated by Django 3.1.6 on 2021-02-24 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_post_private'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='image',
            field=models.CharField(default=0, max_length=255),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.CharField(default=0, max_length=255),
        ),
    ]
