# Generated by Django 3.1.6 on 2021-03-01 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_auto_20210224_0014'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'permissions': [('author', 'author')]},
        ),
    ]
